// Fingerprints src/ into a constant the app renders, so a stale build can be
// detected: verify-build.mjs asserts this exact value reached the bundle.
// Builds in this container have silently reused stale compiler output more than
// once, shipping a bundle that did not match source.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { posix } from 'node:path';

const STAMP_FILE = 'src/app/core/build-stamp.ts';

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = posix.join(dir, name);
    if (p === STAMP_FILE) return []; // excluded, or the hash chases itself
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const h = createHash('sha256');
for (const f of walk('src').sort()) h.update(f).update(readFileSync(f));
const stamp = h.digest('hex').slice(0, 12);

writeFileSync(
  STAMP_FILE,
  `// Generated by scripts/stamp.mjs — do not edit.\nexport const BUILD_STAMP = '${stamp}';\n`,
);
console.log('build stamp', stamp);
